stages:
  - build
  - test

maven-build:
  stage: build
  script:
    - cd floodlight
    - mvn package -Dmaven.test.skip=true

tarn-test:
  stage: test
  script:
    - vagrant up
    - vagrant ssh -c "sudo pip install -U pytest"
    - vagrant ssh -c "sudo pytest ./TARN/mininet/"
    - vagrant destroy -f