stages:
  - build
  - test
  - review
  - cleanup

build_job:
  stage: build
  script:
    - cd floodlight
    - mvn package -Dmaven.test.skip=true

test_job:
  stage: test
  script:
    - vagrant status
    - vagrant up
    - vagrant ssh -c "sudo pip install -U pytest"
    - vagrant ssh -c "sudo pytest ./TARN/mininet/"
  after_script:
    - vagrant status
    
review_job:
  stage: review
  script:
    - vagrant status
    - vagrant ssh -c "cat ./TARN/logs/c1.log"
  when: on_failure
    
cleanup_job:
  stage: cleanup
  script:
    - vagrant status
    - vagrant destroy -f
  when: always