stages:
  - build
  - test

build_job:
  stage: build
  script:
    - cd floodlight
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - ./floodlight/target/floodlight.jar
    expire_in: 1 day

test_job:
  stage: test
  script:
    - vagrant up
    - vagrant ssh -c "sudo pip install -U pytest"
    - vagrant ssh -c "sudo pytest ./TARN/mininet/"
  after_script:
    - vagrant destroy -f