#!/bin/sh

sudo apt-get update  

sudo apt-get install -y ant autoconf automake build-essential debhelper fakeroot git graphviz help2man libssl-dev \
libtool linux-headers-$(uname -r) maven python-all python-paramiko python-pip python-qt4 python-setuptools python-sphinx \
python-twisted-conch quagga tmux vim
  
sudo pip install \
alabaster \
jprops \
pick \
pytest \
requests
